### ISSUE TITLE
AttributeError while running masker-corrector with heuristic masking

### ISSUE THREAD

**Issue by vnik18** [j6mes/acl2021-factual-error-correction#1]
Hi, thank you for sharing your code! While running the masker-corrector model with the following command: `bash scripts/finetune_masked.sh t5-base 1e-4 heuristic true false all`, I get the below error:

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/t5-error-correction/src/error_correction/corrector/run.py", line 83, in <module>
    main(args)
  File "/home/ubuntu/t5-error-correction/src/error_correction/corrector/run.py", line 48, in main
    model: ErrorCorrectionModule = ErrorCorrectionModule(args)
  File "/home/ubuntu/t5-error-correction/src/error_correction/modelling/error_correction_module.py", line 65, in __init__
    super().__init__(hparams, num_labels=None, mode=self.mode, **kwargs)
  File "/home/ubuntu/t5-error-correction/src/error_correction/modelling/base_transformer.py", line 67, in __init__
    self.hparams = hparams
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 819, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

Could you please look into this and tell me where the issue might be? Thank you!

**Comment by j6mes** [comment]
I've seen this before. Can you please check the versions of the libraries you are using? With the wrong version of transformers and pytorch lightning, you might get this error. It should be v3.5.1 for transformers and 0.8.5 for pytorch-lightning

**Comment by vnik18** [comment]
Thank you. Downgrading the version of pytorch-lightning solved the issue.
